version: '3.9'

services:
  postgres:
    image: postgres:alpine
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: rinha_pass
      POSTGRES_USER: rinha_user
      POSTGRES_DB: rinha_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: 'postgres -c max_connections=1000 -c shared_buffers=128MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off'
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U rinha_user -d rinha_db'" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s